### ISSUE TITLE
Not an issue: Can we read ui events of Device and store them in our local java app

### ISSUE THREAD

**Issue by bitquality** [AaronDP/adbfd#2]
Hi,

Can we read ui events of Device and store them in our local java app ? I want to record those events. Or is it better to use logcat ?

Thank you.

**Comment by AaronDP** [comment]
I believe that you will need to use logcat, or create a listener for the events you want. This project creates a daemon (telnetd) that will listen and send on two FIFO files (created using Jackpal TERM), and launched using the "adb" user (over serial). The end result is that you have a bash prompt with adb permissions installed on your device. This would give the ability to read the screen, tap on the screen, install and uninstall software the same way the "adb" user can. This is the _only_ way to elevate your user permissions without rooting, and without having any "buggy" TCP listener installed. The daemon should patiently wait for a connection to the two FIFO files at any time before the devices next reboot while using very few resources. Also, the other advantage of this procedure, is you dont have to open ports, change wifi settings, wait for locks to clear, etc.

-Aaron D. P. 

P.S. This method requires the FIFO to be created by the JackPal terminal user, and then _linked to_ by the adb user. This is important, as in Android 4.4 any FIFOs created by the adb user **cannot be deleted** without root. But, the Jackpal TERM app can be removed at a later time, including any special files it has made such as fifos.
